### PR TITLE
Add map/struct, key/value snippets

### PR DESCRIPTION
**Pull request by jefffederman**

### CODE REVIEW

**Comment by jefffederman** [comment]
Will change snippet names with colons (breaks Windows) in this PR once https://github.com/elixir-lang/elixir-tmbundle/pull/88 is merged into `master`.

**Comment by jefffederman** [comment]
No more colons in names!

**Comment by jefffederman** [comment]
Rebased against latest `master`, now with colons back in snippet names (when appropriate) but no colons in snippet file names.

**Comment by endersstocker** [comment]
Does this work on Windows?

**Comment by jefffederman** [comment]
@endersstocker It should work on Windows, there are no colons in snippet file names.

**Comment by endersstocker** [comment]
:shaved_ice:

**Pull request merged**
