### PR TITLE
Add snippets for def with guard clause

### PR DESCRIPTION
**Pull request by jefffederman**
Also account for args in def snippets.

### CODE REVIEW

**Comment by jefffederman** [comment]
Will change snippet names with colons (breaks Windows) in this PR once https://github.com/elixir-lang/elixir-tmbundle/pull/88 is merged into `master`.

**Comment by jefffederman** [comment]
@josevalim Rebased vs latest `master` with Windows-friendly snippet file names.

**Comment by endersstocker** [comment]
This `def` snippet assume too much. It is better to leave the function signature completely open-ended than to presume arguments and parentheses.

**Comment by josevalim** [comment]
Closing as per @endersstocker feedback.

**Pull request closed without merging**
