### PR TITLE
Auto-match `#{}` within strings

### LINKED ISSUE #96: Add interpolated string Snippet
When in a string, typing `$` should expand to `${}` with the cursor between the brackets. Also when text is selected, and `$` is typed, the text should be wrapped in brackets with the `$` preceding them.

This would be identical in behaviour to the `#` snippet in the Ruby package: https://github.com/textmate/ruby.tmbundle/blob/master/Snippets/embed%20string%20variable.plist

I had a go at doing this myself, but my lack of familiarity with the santa descriptors let me down.

### PR DESCRIPTION
**Pull request by xtian**
I just copied this from the Sublime Ruby package. It address #96.

### CODE REVIEW

**Comment by josevalim** [comment]
Should we rename the file though?

**Comment by xtian** [comment]
To what?

**Comment by josevalim** [comment]
Oh, ignore me. I thought it said something specific to sublime by accident but it is specific to sublime it seems. :D

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by xtian** [comment]
Thanks!

**Pull request merged**
