### PR TITLE
Remove `key: value` snippet

### PR DESCRIPTION
**Pull request by xtian**
I think `key: value` is easy enough to type without a snippet, and having both `:` and `::` bound to snippets causes an autocomplete menu to display when triggering on `::`.

Example:
screen shot 2016-08-10 at 4 58 55 pm

### CODE REVIEW

**Comment by josevalim** [comment]
I would like to get some more feedback here in that `:

**Comment by princemaple** [comment]
+1 on removing it

**Comment by josevalim** [comment]
I would like to propose to remove `::` instead. Using `::` for => is confusing specially because we may use `::` for types.

**Comment by talklittle** [comment]
👍 on removing both `:` and `::`

**Comment by hedgesky** [comment]
Can't say anything about TextMate, but in Sublime Text these snippets's behavior is a bit strange: sometimes autocomplete popup triggers only after several `tab` strokes, sometimes it doesn't appear completely, sometimes first snippet is autoapplied.
+1 for remove both.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
