### PR TITLE
Improve module definition syntax

### PR DESCRIPTION
**Pull request by endersstocker**
**Before**
before

**After**
after

### CODE REVIEW

**Comment by ericmj** [comment]
Thank you!

**Comment by ericmj** [comment]
@endersstocker BTW, any chance we can get syntax highlighting for modules `Foo.Bar`? Or maybe it's already highlighted, I may just be missing something in my config?

**Comment by endersstocker** [comment]
@ericmj I’m not sure I understand, but I’m happy to give it a go. Could you provide a code example and identify the portion that should be matched?

**Comment by ericmj** [comment]
I would like `GenServer` to be highlighted here:

screen shot 2015-09-11 at 03 36 00

**Comment by endersstocker** [comment]
The selector is `support.type.elixir`. It’s not really an accurate name, but most existing themes use `support.type`.

**Pull request merged**
